name: Block Refactor Merges

on:
  pull_request:
    branches:
      - '**'

jobs:
  block-refactor-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          echo "Source branch: $SOURCE_BRANCH"

          if [[ "$SOURCE_BRANCH" == "refactor" ]]; then
            echo "Merging from 'refactor' is not allowed. ❌"
            exit 1
          else
            exit 0
          fi
