# name: Build and Push Java App

# on:
#   workflow_dispatch:

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up JDK 17
#         uses: actions/setup-java@v4
#         with:
#           distribution: 'temurin'
#           java-version: '17'

#       - name: Build with Maven
#         run: mvn clean package --no-transfer-progress

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build Docker image
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/java-app:latest .

#       - name: Push Docker image
#         run: |
#           docker push ${{ secrets.DOCKER_USERNAME }}/java-app:latest


name: Build and Push Java App to JFrog

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: uhg-runner

    env:
      IMAGE_NAME: java-app
      VERSION_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Log in to JFrog Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_REGISTRY }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ARTIFACTORY_REGISTRY }}/dms-poc-github/java-app:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ARTIFACTORY_REGISTRY }}/dms-poc-github/java-app:latest
